#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/b1d137f0-28de-49a2-bfb6-ab3810696827 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String msg;
  int data;
  bool btn;
  bool sw;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include <M5Core2.h>
#include "thingProperties.h"

void setup() {
  M5.begin();
  M5.Lcd.println("Initialized");

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  M5.update();
  ArduinoCloud.update();
  
  if (M5.BtnA.wasPressed()) {    //If the key is pressed. 
    M5.Lcd.println("Button A is pressed.");
    msg = "Button A is pressed.";
  }
  if (M5.BtnB.wasPressed()) {    //If the key is pressed. 
    M5.Lcd.println("Button B is pressed.");
    msg = "Button B is pressed.";
  }
  if (M5.BtnC.wasPressed()) {    //If the key is pressed. 
    M5.Lcd.println("Button C is pressed.");
    msg = "Button C is pressed.";
  }
  
  data = random(100);
  
  delay(500);
}

/*
  Since Msg is READ_WRITE variable, onMsgChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMsgChange()  {
  // Add your code here to act upon Msg change
  M5.Lcd.print(msg);
}

/*
  Since Sw is READ_WRITE variable, onSwChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwChange()  {
  // Add your code here to act upon Sw change
  if(sw){
    M5.Lcd.fillScreen(WHITE);
  }
  else{
    M5.Lcd.fillScreen(BLACK);
  }
}

/*
  Since Btn is READ_WRITE variable, onBtnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBtnChange()  {
  // Add your code here to act upon Btn change
  M5.Lcd.clear();
}